services:
  grafana:
    build:
      context: ./grafana
      args:
        GRAFANA_TOKEN: ${GRAFANA_TOKEN}
        WEBEX_ROOM_ID: ${WEBEX_ROOM_ID}
        GRAFANA_VERSION: ${GRAFANA_VERSION}
        GRAFANA_WEBHOOK: ${GRAFANA_WEBHOOK}
        GRAFANA_WEBHOOK2: ${GRAFANA_WEBHOOK2}
        WEBEX_TEAMS_ACCESS_TOKEN: ${WEBEX_TEAMS_ACCESS_TOKEN}
    container_name: grafana
    ports:
      - "3000:3000"

  influxdb:
    build:
      context: ./influxdb
      args:
        INFLUXDB_VERSION: ${INFLUXDB_VERSION}
        DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
        DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
        DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
        DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
        DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/lib/influxdb2

  telegraf:
    build:
      context: ./telegraf
      args:
        TELEGRAF_VERSION: ${TELEGRAF_VERSION}
        TELEGRAF_ORG: ${TELEGRAF_ORG}
        TELEGRAF_TOKEN: ${TELEGRAF_TOKEN}
        TELEGRAF_BUCKET: ${TELEGRAF_BUCKET}
    container_name: telegraf
    ports:
      - "57500:57500"
    cap_add:
      - NET_RAW

volumes:
  influxdb:
